version: '3'
networks:
  laravel:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - /d/laravel:/var/www
      - /d/laravel/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - web
    networks:
      - laravel
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelApp
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    working_dir: /var/www
    volumes:
      - /d/laravel:/var/www
    depends_on:
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "33061:3306"
    restart: unless-stopped
    tty: true
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - mysql
    ports:
      - "8088:80"
    networks:
      - laravel
  composer:
    image: composer:latest
    command: composer install
    working_dir: /var/www
    volumes:
      - /d/laravel:/var/www
    depends_on:
      - web
    networks:
      - laravel

